---
# playbook.yml
- name: 'Configure Instance'
  hosts: runner
  become: true

  tasks:
    - name: Make sure a service unit is running
      systemd:
        enabled: yes 
        state: stopped
        daemon_reload: yes
        name: github-runners.service
        

