---
# playbook.yml
- name: 'Configure Instance'
  hosts: runner
  become: true

  tasks:
    - name: Installing required packages
      apt:
        pkg: 
          - docker.io
        update_cache: yes
    - name: Copy service file
      copy:
        src: etc/systemd/system/github-runners.service
        dest: /etc/systemd/system/github-runners.service
        owner: root
        group: root
        mode: '0644'
    - name: Copy service file
      template:
        src: ephemeral-github-actions-runner-{{runner_scope}}.env.j2
        dest: /etc/ephemeral-github-actions-runner.env
    - name: Make sure a service unit is running
      systemd:
        enabled: yes 
        state: restarted
        daemon_reload: yes
        name: github-runners.service
        

